name: Build data archive

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - 'data/**/*.toml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-tools:
    uses: ./.github/workflows/install-tools.yml

  build:
    # Grant `GITHUB_TOKEN` the necessary permissions.
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch contributors
        run: just fetch-contributors

      - name: Write commit hash to file
        run: git rev-parse --short HEAD > data/commithash.txt

      - name: Write timestamp to file
        run: date --iso-8601=seconds --utc > data/timestamp.txt

      - name: Create archive
        run: tar cJf data.tar.xz data/

      - name: Configure Git user
        run: |
          git config user.name "workflow"
          git config user.email "workflow@invalid"

      - name: Create new branch
        run: git switch --orphan dist

      - name: Add, commit, and push files
        run: |
          git add data.tar.xz
          git commit -m 'Add data archive'
          git push --force origin dist
