name: Validate and bundle data

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'data/**/*.toml'
      - 'justfile'
      - 'schemas/*.json'
      - 'tools/*.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  build-data-archive:
    needs: validate
    uses: ./.github/workflows/build-data-archive.yml
    if: ${{ github.ref_name == 'main' }}
