name: Validate data files

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'data/**/*.toml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-tools:
    uses: ./.github/workflows/install-tools.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate party series TOML file
        run: just validate-series

      - name: Validate party TOML files
        run: just validate-parties

      - name: Ensure that parties are in the past
        run: just validate-party-dates
